/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Item;
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author mathe
 */
public class SelectedItens extends javax.swing.JFrame {

    private static String[] info;

    Item item = new Item();
    Map<Integer, ArrayList<Item>> itens = new HashMap<>();
    int codigo;

    public SelectedItens() {

        initComponents();
    }

    public void setInfo(String[] info) {
        this.info = info;
    }

    public void showTime(){
        resultadoCompra.setText("");
        this.show();
    }
    
    public void displayProduto() {
        itens = item.getItens();
        codigo = Integer.parseInt(info[0]);
        if (itens.containsKey(codigo)) {
            for (int i = 0; i < itens.get(codigo).size(); i++) {
                if (itens.get(codigo).get(i).getLoja().getNome().equals(info[1])) {
                    item = itens.get(codigo).get(i);
                    nomeProduto.setText(item.getProduto().getNome());
                    lojaProduto.setText(item.getLoja().getNome());
                    precoProduto.setText("R$" + item.getValor());
                    qtdProduto.setText("" + item.getQuantidade());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeProduto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        precoProduto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lojaProduto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        qtdProduto = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        qtdComprar = new javax.swing.JSpinner();
        resultadoCompra = new javax.swing.JLabel();

        setTitle("Quantidade");

        nomeProduto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nomeProduto.setText("jLabel1");

        jLabel1.setText("Preço:");

        precoProduto.setText("xxx");

        jLabel2.setText("Loja:");

        lojaProduto.setText("xxx");

        jLabel3.setText("Qtd:");

        qtdProduto.setText("xxx");

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade à comprar:");

        resultadoCompra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lojaProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qtdComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addComponent(nomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(precoProduto))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(qtdProduto)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(resultadoCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnComprar)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(precoProduto)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lojaProduto)
                    .addComponent(qtdComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(qtdProduto)
                    .addComponent(resultadoCompra))
                .addGap(44, 44, 44)
                .addComponent(btnComprar)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        int qtd = Integer.parseInt(qtdComprar.getValue().toString());
        if (item.getQuantidade() > 0) {
            if (item.getQuantidade() >= qtd) {
                
                for(int i=0;i<itens.get(codigo).size();i++){
                    if (itens.get(codigo).get(i).getLoja().getNome().equals(info[1])) {
                        itens.get(codigo).get(i).setQuantidade(item.getQuantidade() - qtd);
                        item.setItens(itens);
                        qtdProduto.setText(""+(item.getQuantidade()));
                        resultadoCompra.setForeground(Color.green);
                        resultadoCompra.setText("Compra feita com sucesso !");
                  }
                }
            } else {
                resultadoCompra.setForeground(Color.red);
                resultadoCompra.setText("Quantidade indisponível !");
            }
        } else {
            resultadoCompra.setForeground(Color.red);
            resultadoCompra.setText("EM FALTA !");
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectedItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectedItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectedItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectedItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectedItens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lojaProduto;
    private javax.swing.JLabel nomeProduto;
    private javax.swing.JLabel precoProduto;
    private javax.swing.JSpinner qtdComprar;
    private javax.swing.JLabel qtdProduto;
    private javax.swing.JLabel resultadoCompra;
    // End of variables declaration//GEN-END:variables
}
